<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formation FullStack — 2ème année —</title>
    <style>
        :root { --navy:#0f172a; --blue:#2563eb; --sky:#dbeafe; --slate:#64748b; --line:#e2e8f0; --page:#f5f7fb; }
        * { box-sizing:border-box; margin:0; padding:0; } html { scroll-behavior:smooth; }
        body { font-family:Arial,Helvetica,sans-serif; background:var(--page); color:#1e293b; }
        header { position:sticky; top:0; z-index:10; display:flex; align-items:center; justify-content:space-between; padding:18px 7%; background:var(--navy); color:#fff; }
        .logo { font-size:22px; font-weight:700; }.logo span { color:#38bdf8; } nav { display:flex; gap:25px; } nav a { color:#cbd5e1; font-size:15px; text-decoration:none; } nav a:hover { color:#fff; }
        .menu-toggle { display:none; padding:9px 12px; border:1px solid #475569; border-radius:8px; background:transparent; color:#fff; cursor:pointer; }
        .hero { padding:75px 7%; color:#fff; background:linear-gradient(135deg,var(--navy),#1e3a8a); }.hero-content { max-width:850px; }
        .badge { display:inline-block; margin-bottom:20px; padding:8px 15px; border:1px solid rgba(255,255,255,.2); border-radius:20px; background:rgba(255,255,255,.12); font-size:13px; }
        h1 { margin-bottom:18px; font-size:45px; } h1 span { color:#38bdf8; }.hero p { max-width:750px; color:#dbeafe; font-size:18px; line-height:1.7; }
        .container { width:86%; max-width:1200px; margin:auto; } section { padding:45px 0; }.section-title { margin-bottom:22px; }.section-title h2 { margin-bottom:8px; font-size:28px; }.section-title p,.module-title p,small { color:var(--slate); }
        .module { margin-bottom:32px; padding:30px; border:1px solid var(--line); border-radius:16px; background:#fff; box-shadow:0 5px 20px rgba(15,23,42,.07); scroll-margin-top:85px; }.module-header { display:flex; align-items:center; gap:20px; margin-bottom:28px; }.module-number { display:grid; flex:0 0 55px; width:55px; height:55px; place-items:center; border-radius:14px; background:var(--sky); color:#1d4ed8; font-size:17px; font-weight:700; }.module-title h3 { margin-bottom:5px; font-size:24px; }
        .module-content { padding-top:4px; }.content-heading { margin:26px 0 12px; font-size:19px; }.content-heading:first-child { margin-top:0; }
        .cards { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; }.card { display:flex; flex-direction:column; padding:22px; border:1px solid var(--line); border-radius:14px; background:#fff; }.card:hover { transform:translateY(-3px); box-shadow:0 10px 25px rgba(15,23,42,.09); transition:.2s; }.card-icon { margin-bottom:12px; font-size:26px; }.card h4 { margin-bottom:9px; font-size:18px; }.card p { flex:1; margin-bottom:16px; color:var(--slate); font-size:14px; line-height:1.55; }
        .resource-list { display:flex; flex-direction:column; gap:10px; }.resource { display:flex; align-items:center; justify-content:space-between; gap:15px; padding:13px 16px; border:1px solid var(--line); border-radius:10px; background:#fff; }.resource-info { display:flex; align-items:center; gap:13px; }.file-icon { display:grid; flex:0 0 40px; width:40px; height:40px; place-items:center; border-radius:8px; background:#fee2e2; color:#dc2626; font-size:11px; font-weight:bold; }.resource strong { display:block; margin-bottom:3px; }
        .btn { display:inline-block; padding:10px 14px; border-radius:8px; font-size:14px; font-weight:bold; text-decoration:none; white-space:nowrap; }.btn-primary { background:var(--blue); color:#fff; }.btn-primary:hover { background:#1d4ed8; }.btn-outline { border:1px solid #cbd5e1; color:#334155; }.btn-outline:hover { background:#f1f5f9; }
        .subtopics { display:grid; grid-template-columns:repeat(2,1fr); gap:18px; }.topic { padding:24px; border:1px solid var(--line); border-radius:14px; background:#f8fbff; }.topic h4 { margin:8px 0; font-size:19px; }.topic p { color:var(--slate); line-height:1.55; }.topic-label { color:#1d4ed8; font-size:13px; font-weight:bold; text-transform:uppercase; }.project { margin-top:26px; padding:28px; border-radius:16px; background:var(--navy); color:#fff; }.project h3 { margin-bottom:10px; font-size:23px; }.project p { max-width:800px; margin-bottom:18px; color:#cbd5e1; line-height:1.6; }.empty { padding:18px; border:1px dashed #cbd5e1; border-radius:10px; color:var(--slate); background:#fff; } footer { margin-top:25px; padding:30px; background:var(--navy); color:#94a3b8; text-align:center; } footer p + p { margin-top:5px; }
        @media (max-width:850px) { header { flex-wrap:wrap; padding:14px 7%; }.menu-toggle { display:block; } nav { display:none; width:100%; flex-direction:column; gap:4px; padding-top:12px; } nav.is-open { display:flex; } nav a { padding:11px; border-radius:8px; } nav a:hover { background:#1e293b; }.cards,.subtopics { grid-template-columns:1fr; }.module-header { align-items:flex-start; }.resource { align-items:flex-start; flex-direction:column; } h1 { font-size:34px; } }
    </style>
</head>
<body>
<header>
    <div class="logo">Full<span>Stack</span> Academy</div><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-navigation">Menu</button><nav id="main-navigation"><a href="#modules">Modules</a><a href="#m01">M01 : Projet Web</a><a href="#m02">M02 : Gestion de projets</a><a href="#portfolio-en-ligne">Portfolio en ligne</a><a href="#badge-portfolio">Badge portfolio</a></nav></header>
<section class="hero"><div class="hero-content"><div class="badge">Formation Développement Web FullStack</div><h1>2ème année <span>FullStack</span></h1><p>Un espace pédagogique organisé par modules. Chaque module regroupe ses cours, travaux pratiques, exercices et projets.</p></div></section>
<main class="container"><section id="modules"><div class="section-title"><h2>Parcours de formation</h2><p>Choisissez un module pour accéder à l'ensemble de ses ressources.</p></div>
<article class="module" id="m01"><div class="module-header"><div class="module-number">M01</div><div class="module-title"><h3>Préparer un projet Web</h3><p>Analyse, conception, organisation et préparation d'un projet Web avant son développement.</p></div></div>
<div class="module-content" id="m01-cours"><h4 class="content-heading">Cours — UML</h4><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">PPT</div><div><strong>Cours — UML</strong><small>Support principal de modélisation</small></div></div><a href="/docs/UML.pptx" class="btn btn-primary" download>Télécharger</a></div><div class="resource"><div class="resource-info"><div class="file-icon">PNG</div><div><strong>UML — Résumé</strong><small>Modélisation et conception</small></div></div><a href="/images/résumeuml.png" class="btn btn-primary" download>Télécharger</a></div><div class="resource"><div class="resource-info"><div class="file-icon">PDF</div><div><strong>Exercices UML</strong><small>Exercices de modélisation et conception</small></div></div><a href="/docs/UMLTPs.pdf" class="btn btn-primary" download>Télécharger</a></div></div>
<h4 class="content-heading">Cours — UX / UI Figma</h4><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">PPT</div><div><strong>Présentation Figma</strong><small>Support d'introduction à Figma</small></div></div><a href="/docs/Figma.pptx" class="btn btn-primary" download>Télécharger</a></div><div class="resource"><div class="resource-info"><div class="file-icon">VID</div><div><strong>Figma — Partie 1</strong><small>Outils de base</small></div></div></div><div class="resource"><div class="resource-info"><div class="file-icon">VID</div><div><strong>Figma — Partie 2</strong><small>Outils avancés</small></div></div></div><div class="resource"><div class="resource-info"><div class="file-icon">VID</div><div><strong>Figma — Partie 3</strong><small>Prototypage et animations</small></div></div></div></div>
<h4 class="content-heading" id="m01-tp">Travaux pratiques</h4><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">TP</div><div><strong>Atelier — Application de gestion d'une société immobilière</strong><small>Cas d'utilisation, classes et scénarios UML</small></div></div><a href="/docs/UML_gestion_immobilier.pdf" class="btn btn-primary" download>Énoncé PDF</a></div></div><div class="project" id="m01-projet"><h3>Mini-projet — Application Web</h3><p>Réalisez une application Web en appliquant les étapes étudiées : analyse du besoin, conception, modélisation UML et préparation du projet.</p><a href="/docs/quickannonces.pdf" class="btn btn-primary" download>Télécharger l'énoncé PDF</a></div></div></article>
<article class="module" id="m02"><div class="module-header"><div class="module-number">M02</div><div class="module-title"><h3>Gestion de projets</h3><p>Découvrir et mettre en œuvre les principales approches d'organisation et de pilotage d'un projet.</p></div></div><div class="subtopics"><section class="topic"><div class="topic-label">Axe 1</div><h4>Modèle en cascade (Waterfall)</h4><p>Planifier les phases du projet de façon séquentielle : besoins, conception, développement, tests et livraison.</p></section><section class="topic"><div class="topic-label">Axe 2</div><h4>Agile Scrum</h4><p>Organiser le projet en itérations courtes avec un backlog, des sprints, des rôles définis et une amélioration continue.</p></section></div><h4 class="content-heading">Cours et outils du module</h4><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">PPT</div><div><strong>Cours — Gestion de projets</strong><small>Support couvrant le modèle en cascade et l'approche Agile Scrum</small></div></div><a href="/docs/cours-gestion-de-projet-Agile.pptx" class="btn btn-primary" download>Télécharger</a></div><div class="resource"><div class="resource-info"><div class="file-icon">VID</div><div><strong>Démo vidéo — Diagramme de PERT et chemin critique</strong><small>Vidéo explicative sur le PERT et le chemin critique</small></div></div><a href="https://www.youtube.com/watch?v=ZSvt-TcxqrE&feature=youtu.be" class="btn btn-primary" target="_blank" rel="noopener noreferrer">Voir la démo</a></div>
    <div class="resource"><div class="resource-info">
        <div class="file-icon">PDF</div><div><strong>Atelier 1 — Gestion de projet : Méthodes classiques</strong><small>Support de l'atelier sur les méthodes classiques de gestion de projet</small></div>
         </div><a href="/docs/At1_gestionprojet.pdf" class="btn btn-primary" download>Télécharger</a></div>
        <div class="file-icon">PDF</div><div><strong>Atelier 2 — Gestion de projet : Agile Scrum</strong><small>Support de l'atelier sur le framwork Agile scrum</small></div>
         </div><a href="/docs/At2_gestionprojet.pdf" class="btn btn-primary" download>Télécharger</a></div>
         
         <div class="resource"><div class="resource-info"><div class="file-icon">APP</div><div><strong>GanttProject</strong><small>Outil de planification et de création de diagrammes de Gantt</small></div></div><a href="https://en.softonic.com/download/ganttproject/windows/post-download?dt=internalDownload&amp;installerType=riseInstaller" class="btn btn-primary" target="_blank" rel="noopener noreferrer">Télécharger GanttProject</a></div></div></article>
</section><section id="portfolio-en-ligne"><div class="section-title"><h2>Créer son portfolio en ligne</h2><p>Suivez le guide et récupérez le fichier de configuration nécessaires pour publier votre portfolio sur Vercel.</p></div><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">PDF</div><div><strong>Guide d'hébergement sur Vercel</strong><small>Étapes pour mettre votre portfolio en ligne.</small></div></div><a href="/docs/guide_hostingvercel.pdf" class="btn btn-primary" download>Télécharger le guide</a></div><div class="resource"><div class="resource-info"><div class="file-icon">JSON</div><div><strong>Fichier de configuration Vercel</strong><small>Fichier vercel.json nécessaire pour déployer le projet sur Vercel.</small></div></div><a href="/docs/vercel.json" class="btn btn-primary" download="vercel.json">Télécharger vercel.json</a></div></div></section><section id="badge-portfolio"><div class="section-title"><h2>Créer un badge portfolio</h2><p>Créez un badge personnalisé pour votre portfolio avec l'application React.</p></div><div class="resource-list"><div class="resource"><div class="resource-info"><div class="file-icon">APP</div><div><strong>Générateur de badge portfolio</strong><small>Ouvrez l'application pour créer votre badge.</small></div></div><a href="https://badge-ashen-two.vercel.app/" class="btn btn-primary" target="_blank" rel="noopener noreferrer">Créer un badge</a></div></div></section></main>
<footer><p>Formation Développement Web FullStack — 2ème année</p><p>Espace pédagogique stagiaires</p></footer>
<script>const menuToggle=document.querySelector('.menu-toggle'),navigation=document.querySelector('#main-navigation');menuToggle.addEventListener('click',()=>{const open=navigation.classList.toggle('is-open');menuToggle.setAttribute('aria-expanded',open);menuToggle.textContent=open?'Fermer':'Menu'});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{if(window.innerWidth<=850){navigation.classList.remove('is-open');menuToggle.setAttribute('aria-expanded','false');menuToggle.textContent='Menu'}}));</script>
</body>
</html>
